name: 'alipay-cloud-devops-codescan'
description: 'Greet someone and record the time'
inputs:
    parent_uid:  # id of input
        description: 'a param to get token'
        required: true
    private_key:  # id of input
        description: 'another param to get token'
        required: true
    scan_type: #  type of input
        description: 'stc for security check , sca for open source compliance check'
        required: true
    tips: #  prompt
        description: 'prompt tips'
        required: false
        default: ' '
    cybersec_token: #   cybersec_token
        description: 'token for cybersec'
        required: false
        default: ' '
outputs:
    result: # id of output
        description: 'code scan passed or not'
runs:
    using: 'node16'
    main: 'dist/index.js'
